spring:
  application:
    name: ai-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  session:
    timeout: 86400
server:
  port: 8088
  servlet:
    context-path: /api

# MyBatis-Flex配置
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    normal-value-of-logic-delete: 0
    deleted-value-of-logic-delete: 1

# springdoc-openapi????
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xc.java.aicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn